version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
      
  pre_build:
    commands:
    - npm install -g pnpm
    - pnpm install --frozen-lockfile
    
  build:
    commands:
    - pnpm build   
