version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
      
  pre_build:
    commands:
    - npm install -g pnpm
    - pnpm install --frozen-lockfile
    
  build:
    commands:
    - pnpm build
  
  post_build:
    commands:
    - aws s3 sync --delete ./dist s3://${BUCKET_NAME}
    - aws cloudfront create-invalidation --distribution-id ${CF_ID} --paths "/*"
