name: ci_cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Linting
        run: pnpm lint
        env:
          CI: true

      - name: Type checking
        run: pnpm type-check
        env:
          CI: true

      - name: Unit Tests
        run: pnpm test:unit
        env:
          CI: true
        
      - name: Build
        run: pnpm build
        env:
          CI: true
          
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: E2E Tests
        run: pnpm test:e2e
        env:
          CI: true


